import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Anchor, LayoutDashboard, KeyRound, ListTodo, Receipt, Settings, LockKeyhole, Plus, Search, ArrowUpRight, Bell, ShieldCheck, Clock3, MoreHorizontal, X, Copy, Eye, EyeOff, RefreshCw, Check, Pause, Play, Trash2, Pencil, Download, Upload, CalendarDays, History, CircleCheck, ChevronRight } from 'lucide-react';
import './style.css';
import { AutomaticBackupPanel } from './AutomaticBackupPanel';

declare global { interface Window { anchor: { call<T = any>(command: string,arg?: any): Promise<T>; onLock(callback: () => void): () => void } } }
const api = <T = any,>(command: string,arg?: any) => window.anchor.call<T>(command,arg);
type Credential = { id?:string;title:string;username:string;url:string;password:string;notes:string;category:string;updatedAt?:string };
type Reminder = {mode?:'deadline'|'ongoing';id?:string;title:string;kind:'task'|'bill';notes:string;amount:number;currency:string;due:string;recurrence:string;every:number;unit:string;leadMinutes:number;repeatMinutes:number;windows:boolean;discord:boolean;enabled:boolean;completed:boolean;nextNotify?:string|null};
type Page = 'overview'|'credentials'|'tasks'|'bills'|'history'|'settings';
const fmtDate = (v:string) => new Date(v).toLocaleString('id-ID',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'});
const money = (v:number,c='IDR') => new Intl.NumberFormat('id-ID',{style:'currency',currency:c,maximumFractionDigits:c === 'IDR' ? 0 : 2}).format(v);
const localDate = (iso:string) => { const d = new Date(iso); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0,19); };
const names: Record<string,string> = {once:'Sekali',daily:'Harian',weekly:'Mingguan',monthly:'Bulanan',yearly:'Tahunan',custom:'Custom'};
const units: Record<string,string> = {seconds:'detik',minutes:'menit',hours:'jam',days:'hari',weeks:'minggu',months:'bulan',years:'tahun'};
const recurrenceLabel = (r:Reminder) => r.recurrence === 'custom' ? `Setiap ${r.every} ${units[r.unit]}` : names[r.recurrence];
const freshReminder = (kind:'task'|'bill'):Reminder => ({title:'',kind,mode:kind === 'task' ? 'ongoing' : 'deadline',notes:'',amount:0,currency:'IDR',due:new Date(Date.now()+3600000).toISOString(),recurrence:kind === 'bill' ? 'monthly':'daily',every:1,unit:'days',leadMinutes:0,repeatMinutes:0,windows:true,discord:false,enabled:true,completed:false});
const hasDeadline = (r:Reminder) => r.mode !== 'ongoing';
const reminderTime = (r:Reminder) => hasDeadline(r) ? r.due : (r.nextNotify || r.due);
const isOverdue = (r:Reminder) => hasDeadline(r) && Date.parse(r.due) < Date.now();
const freshCredential = ():Credential => ({title:'',username:'',url:'',password:'',notes:'',category:'Akun'});

function App() {
  const [page,setPage] = useState<Page>('overview'), [status,setStatus] = useState({initialized:false,unlocked:false}), [ready,setReady] = useState(false);
  const [reminders,setReminders] = useState<Reminder[]>([]), [credentials,setCredentials] = useState<Credential[]>([]), [history,setHistory] = useState<any[]>([]), [settings,setSettings] = useState<any>(null);
  const [query,setQuery] = useState(''), [filter,setFilter] = useState('active'), [toast,setToast] = useState(''), [error,setError] = useState(''), [busy,setBusy] = useState(false);
  const [credential,setCredential] = useState<Credential|null>(null), [reminder,setReminder] = useState<Reminder|null>(null), [auth,setAuth] = useState(false), [backup,setBackup] = useState<'exportBackup'|'importBackup'|null>(null);
  const [confirmation,setConfirmation] = useState<{title:string;body:string;run:()=>Promise<void>}|null>(null);
  async function refresh() {
    const [s,r,h,p] = await Promise.all([api('status'),api('reminders'),api('history'),api('settings')]);
    setStatus(s); setReminders(r); setHistory(h); setSettings(p);
    if (s.unlocked) { try { setCredentials(await api('credentials')); } catch { setCredentials([]); } } else setCredentials([]);
    setReady(true);
  }
  async function act(fn:()=>Promise<any>,message?:string) {
    if (busy) return; setBusy(true); setError('');
    try { await fn(); await refresh(); if (message) setToast(message); }
    catch (e) { setError((e as Error).message); }
    finally { setBusy(false); }
  }
  useEffect(() => { refresh().catch(e=>setError(e.message)); const timer = setInterval(() => { Promise.all([api('reminders'),api('settings')]).then(([r,p]) => {setReminders(r);setSettings(p);}).catch(()=>{}); },15000); return () => clearInterval(timer); },[]);
  useEffect(() => window.anchor.onLock(() => { setStatus(s=>({...s,unlocked:false}));setCredentials([]);setCredential(null);setBackup(null); }),[]);
  useEffect(() => { let last = 0; const activity = () => { if (Date.now()-last > 30000) { last=Date.now(); api('activity').catch(()=>{}); } }; window.addEventListener('pointerdown',activity); window.addEventListener('keydown',activity); return () => { window.removeEventListener('pointerdown',activity);window.removeEventListener('keydown',activity); }; },[]);
  useEffect(() => { if (!toast) return; const t = setTimeout(()=>setToast(''),4500); return ()=>clearTimeout(t); },[toast]);
  useEffect(() => { setQuery('');setFilter('active'); },[page]);
  const active = reminders.filter(r=>r.enabled&&!r.completed), overdue = active.filter(isOverdue);
  const upcoming = [...active].sort((a,b)=>reminderTime(a).localeCompare(reminderTime(b)));
  const currentMonth = new Date().getMonth(), currentYear = new Date().getFullYear();
  const billsThisMonth = active.filter(r=>r.kind==='bill'&&new Date(r.due).getMonth()===currentMonth&&new Date(r.due).getFullYear()===currentYear);
  function navigate(p:Page) { setPage(p);setError(''); }
  function deleteReminder(r:Reminder) { setConfirmation({title:'Hapus reminder?',body:`“${r.title}” akan dihapus. Riwayat penyelesaian tetap disimpan.`,run:async()=>{ await api('deleteReminder',{id:r.id});setConfirmation(null); }}); }
  function complete(r:Reminder) { setConfirmation({title:r.kind==='bill'?'Tandai sudah dibayar?':'Selesaikan task?',body:!hasDeadline(r)?`“${r.title}” akan selesai dan seluruh pengingat berulangnya berhenti.`:r.recurrence==='once'?`“${r.title}” akan ditandai selesai.`:`Periode ${fmtDate(r.due)} akan selesai. Periode berikutnya tetap terjadwal. Jika ada tunggakan beberapa periode, selesaikan satu per satu.`,run:async()=>{await api('reminderAction',{id:r.id,action:'complete'});setConfirmation(null);}}); }
  const reminderRows = (items:Reminder[]) => items.length ? <div className="reminder-list">{items.map(r=><div className="reminder-row" key={r.id}>
    <div className={'item-icon '+(r.kind==='bill'?'purple':'blue')}>{r.kind==='bill'?<Receipt size={20}/>:<ListTodo size={20}/>}</div>
    <div className="reminder-info"><strong>{r.title}</strong><div className="meta"><span>{hasDeadline(r) ? fmtDate(r.due) : 'Tanpa deadline'}</span><span>·</span><span>{recurrenceLabel(r)}</span>{r.repeatMinutes>0&&<span title="Ulangi sampai selesai">· ulang {r.repeatMinutes} menit</span>}</div>{!r.completed&&r.nextNotify&&<div className="next-notice">Notifikasi berikutnya: {fmtDate(r.nextNotify)}</div>}</div>
    <div className="row-value">{r.kind==='bill'&&<strong>{money(r.amount,r.currency)}</strong>}<span className={'badge '+(r.completed?'green':!r.enabled?'neutral':isOverdue(r)?'red':'blue')}>{r.completed?'Selesai':!r.enabled?'Nonaktif':isOverdue(r)?'Terlewat':'Terjadwal'}</span></div>
    <div className="row-actions">{!r.completed&&<><button className="icon-button" title={r.kind==='bill'?'Sudah dibayar':'Selesai'} aria-label={`Selesaikan ${r.title}`} disabled={busy} onClick={()=>complete(r)}><Check size={18}/></button><button className="icon-button" title="Snooze 30 menit" disabled={busy||!r.enabled} onClick={()=>act(()=>api('reminderAction',{id:r.id,action:'snooze',minutes:30}),'Ditunda 30 menit')}><Clock3 size={18}/></button><button className="icon-button" title={r.enabled?'Nonaktifkan jadwal':'Aktifkan jadwal'} disabled={busy} onClick={()=>act(()=>api('reminderAction',{id:r.id,action:'toggle'}))}>{r.enabled?<Pause size={17}/>:<Play size={17}/>}</button></>}<button className="icon-button" title="Edit reminder" onClick={()=>setReminder({...r})}><Pencil size={16}/></button><button className="icon-button danger-icon" title="Hapus reminder" onClick={()=>deleteReminder(r)}><Trash2 size={16}/></button></div>
  </div>)}</div> : <Empty icon={<CalendarDays/>} title="Belum ada reminder di sini" text="Tambahkan task atau tagihan. Anchor akan mengingatkan saat waktunya tiba."/>;
  if (!window.anchor) return <div className="fatal">Buka Anchor melalui aplikasi desktop. Integrasi lokal tidak tersedia di browser biasa.</div>;
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-icon"><Anchor size={23}/></div><div>Anchor<span>YOUR PERSONAL SPACE</span></div></div>
      <div className="nav-label">WORKSPACE</div><nav>{([['overview',LayoutDashboard,'Ringkasan'],['credentials',KeyRound,'Credentials'],['tasks',ListTodo,'Tasks'],['bills',Receipt,'Bills'],['history',History,'Riwayat']] as const).map(([id,Icon,label])=><button key={id} className={page===id?'selected':''} onClick={()=>navigate(id)}><Icon size={19}/><span>{label}</span>{id==='tasks'&&<small>{active.filter(r=>r.kind==='task').length}</small>}{id==='bills'&&<small>{active.filter(r=>r.kind==='bill').length}</small>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="local-card"><span className="status-dot"/><strong>Disimpan di perangkat ini</strong><p>Personal. Lokal. Dalam kendalimu.</p></div><button className={'settings-nav '+(page==='settings'?'selected':'')} onClick={()=>navigate('settings')}><Settings size={19}/>Pengaturan</button><div className="profile"><div className="avatar">ME</div><div><strong>Personal workspace</strong><span>Hanya untuk kamu</span></div><ShieldCheck size={18}/></div></div>
    </aside>
    <main><header className="topbar"><div className="breadcrumb">Workspace <ChevronRight size={14}/> <strong>{{overview:'Ringkasan',credentials:'Credentials',tasks:'Tasks',bills:'Bills',history:'Riwayat',settings:'Pengaturan'}[page]}</strong></div><div className="top-actions"><span className="local-label"><span className="status-dot"/> Local only</span><button className="vault-status" onClick={()=>status.unlocked?act(()=>api('lock'),'Vault dikunci'):setAuth(true)}><LockKeyhole size={15}/>{status.unlocked?'Kunci vault':'Vault terkunci'}</button></div></header>
    <div className="content">{error&&<div role="alert" className="error-banner">{error}<button aria-label="Tutup error" onClick={()=>setError('')}><X size={16}/></button></div>}
    {!ready?<Empty icon={<Anchor/>} title="Membuka workspace…" text="Menyiapkan penyimpanan lokal."/>:<>
    {page==='overview'&&<><div className="page-heading"><div><div className="eyebrow">{new Date().toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</div><h1>Semua tertata. Pikiran tenang.</h1><p>Akun penting dan hal yang perlu kamu ingat, dalam satu tempat.</p></div><button className="primary" onClick={()=>setReminder(freshReminder('task'))}><Plus size={18}/>Tambah reminder</button></div>
      <div className="stats"><Stat title="Task aktif" value={active.filter(r=>r.kind==='task').length} caption="Hal yang sedang kamu kerjakan" icon={<ListTodo/>}/><Stat title="Tagihan bulan ini" value={billsThisMonth.length} caption="Periode yang belum dibayar" icon={<Receipt/>}/><Stat title="Perlu perhatian" value={overdue.length} caption="Jatuh tempo telah terlewat" icon={<Clock3/>} alert={overdue.length>0}/></div>
      <div className="overview-grid"><section className="panel upcoming"><div className="panel-heading"><div><h2>Agenda terdekat</h2><p>Prioritasmu, di satu tempat.</p></div><button className="text-button" onClick={()=>navigate('tasks')}>Lihat tasks <ArrowUpRight size={15}/></button></div>{reminderRows(upcoming.slice(0,6))}</section>
      <section className="vault-card"><div className="vault-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="safe-icon"><LockKeyhole size={37} strokeWidth={1.5}/></div><span className="spark spark-one"/><span className="spark spark-two"/></div><span className="eyebrow">RUANG AMAN UNTUK AKUNMU</span><h2>Credential vault</h2><p>Simpan akses server, akun billing, dan password dalam vault terenkripsi.</p><button onClick={()=>navigate('credentials')}>Buka credentials <ArrowUpRight size={17}/></button><div className="vault-foot"><ShieldCheck size={14}/>AES-256-GCM · Master password</div></section></div>
      <div className="bottom-note"><Bell size={18}/><div><strong>Anchor tetap siaga di system tray.</strong><span>Menutup jendela tidak menghentikan reminder. PC perlu menyala dan tidak sleep.</span></div><span className="badge green">Scheduler aktif</span></div></>}
    {page==='credentials'&&<><div className="page-heading"><div><div className="eyebrow">PERSONAL VAULT</div><h1>Credentials</h1><p>Akses pentingmu, tersimpan dengan aman di perangkat ini.</p></div><button className="primary" onClick={()=>status.unlocked?setCredential(freshCredential()):setAuth(true)}><Plus size={18}/>Tambah credential</button></div>
      {!status.unlocked?<div className="locked-panel"><div className="locked-icon"><LockKeyhole size={32}/></div><h2>{status.initialized?'Vault terkunci':'Buat ruang aman pertamamu'}</h2><p>{status.initialized?'Masukkan master password untuk melihat dan mengelola credential.':'Buat master password minimal 12 karakter. Password ini tidak dapat di-reset.'}</p><button className="primary" onClick={()=>setAuth(true)}>{status.initialized?'Buka vault':'Buat vault'}</button><span>Reminder tetap berjalan saat vault terkunci.</span></div>:<><div className="toolbar"><div className="search-box"><Search size={17}/><input aria-label="Cari credential" placeholder="Cari nama, username, atau alamat…" value={query} onChange={e=>setQuery(e.target.value)}/></div><span className="muted">{credentials.length} credential</span></div><div className="credential-grid">{credentials.filter(c=>`${c.title} ${c.username} ${c.url} ${c.category}`.toLowerCase().includes(query.toLowerCase())).map(c=><article className="credential-card" key={c.id}><div className="credential-card-top"><div className="item-icon purple"><KeyRound size={21}/></div><span className="badge neutral">{c.category}</span><button className="icon-button" title="Edit credential" onClick={()=>act(async()=>setCredential(await api('credential',{id:c.id})))}><Pencil size={16}/></button></div><h3>{c.title}</h3><p className="credential-user">{c.username||'Tanpa username'}</p><p className="credential-url">{c.url||'Tanpa alamat'}</p><div className="credential-card-bottom"><span>••••••••••••</span><button className="text-button" onClick={()=>act(()=>api('copySecret',{id:c.id}),'Password disalin; clipboard dibersihkan dalam 30 detik')}><Copy size={15}/>Salin password</button></div></article>)}</div>{!credentials.length&&<Empty icon={<KeyRound/>} title="Vault siap diisi" text="Tambahkan credential server, billing, atau akun pertamamu."/>}</>}
    </>}
    {(page==='tasks'||page==='bills')&&<><div className="page-heading"><div><div className="eyebrow">{page==='tasks'?'ONE THING AT A TIME':'STAY ON TOP OF PAYMENTS'}</div><h1>{page==='tasks'?'Tasks & reminders':'Bills & payments'}</h1><p>{page==='tasks'?'Jadwalkan, tunda, dan selesaikan. Biar Anchor yang mengingatkan.':'Pantau jatuh tempo dan catat pembayaran untuk setiap periode.'}</p></div><button className="primary" onClick={()=>setReminder(freshReminder(page==='tasks'?'task':'bill'))}><Plus size={18}/>{page==='tasks'?'Tambah task':'Tambah bill'}</button></div>
      <div className="toolbar"><div className="tabs">{[['active','Aktif'],['paused','Nonaktif'],['done','Selesai'],['all','Semua']].map(([v,label])=><button key={v} className={filter===v?'active':''} onClick={()=>setFilter(v)}>{label}</button>)}</div><div className="search-box"><Search size={17}/><input aria-label="Cari reminder" placeholder="Cari reminder…" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><section className="panel">{reminderRows(reminders.filter(r=>r.kind===(page==='tasks'?'task':'bill')&&r.title.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='active'&&r.enabled&&!r.completed||filter==='paused'&&!r.enabled&&!r.completed||filter==='done'&&r.completed)).sort((a,b)=>reminderTime(a).localeCompare(reminderTime(b))))}</section></>}
    {page==='history'&&<><div className="page-heading"><div><div className="eyebrow">A LITTLE PROGRESS, EVERY DAY</div><h1>Riwayat penyelesaian</h1><p>Task yang selesai dan tagihan yang sudah dibayar. Menampilkan 200 aktivitas terbaru.</p></div></div><section className="panel">{history.length?history.map(h=><div className="history-row" key={h.id}><div className="item-icon green"><CircleCheck size={21}/></div><div className="grow"><strong>{h.title}</strong><div className="meta">{h.mode === 'ongoing' ? 'Tanpa deadline' : `Periode ${fmtDate(h.due)}`} · Selesai {fmtDate(h.completedAt)}</div></div>{h.kind==='bill'&&<strong>{money(h.amount,h.currency)}</strong>}<span className="badge green">{h.kind==='bill'?'Dibayar':'Selesai'}</span></div>):<Empty icon={<CircleCheck/>} title="Awal yang baru" text="Task dan pembayaran yang kamu selesaikan akan muncul di sini."/>}</section></>}
    {page==='settings'&&settings&&<><div className="page-heading"><div><div className="eyebrow">MAKE IT YOURS</div><h1>Pengaturan</h1><p>Atur cara Anchor bekerja untukmu.</p></div></div><SettingsPanel settings={settings} busy={busy} act={act} unlocked={status.unlocked} onUnlock={()=>setAuth(true)} onBackup={setBackup}/></>}
    </>}
    </div></main>
    {toast&&<div role="status" className="toast"><CircleCheck size={18}/>{toast}</div>}
    {auth&&<AuthModal initialized={status.initialized} busy={busy} onClose={()=>setAuth(false)} onSubmit={(password:string)=>act(async()=>{await api(status.initialized?'unlock':'setup',{password});setAuth(false);},'Vault terbuka')}/>}
    {credential&&<CredentialModal initial={credential} busy={busy} onClose={()=>setCredential(null)} onSave={(c:Credential)=>act(async()=>{await api('saveCredential',c);setCredential(null);},'Credential disimpan')} onGenerate={()=>api('generatePassword')} onDelete={()=>setConfirmation({title:'Hapus credential?',body:`“${credential.title}” akan dihapus dari vault.`,run:async()=>{await api('deleteCredential',{id:credential.id});setCredential(null);setConfirmation(null);}})}/>}
    {reminder&&<ReminderModal initial={reminder} busy={busy} onClose={()=>setReminder(null)} onSave={(r:Reminder)=>act(async()=>{await api('saveReminder',r);setReminder(null);},'Reminder disimpan')}/>}
    {backup&&<BackupModal mode={backup} busy={busy} onClose={()=>setBackup(null)} onSubmit={(password:string)=>act(async()=>{ const done=await api(backup,{password});if(done){setBackup(null);setToast(backup==='exportBackup'?'Backup terenkripsi disimpan':'Backup digabungkan ke workspace');} })}/>}
    {confirmation&&<Modal title={confirmation.title} onClose={()=>setConfirmation(null)}><p className="dialog-copy">{confirmation.body}</p><div className="modal-footer"><button className="secondary" onClick={()=>setConfirmation(null)}>Batal</button><button className="primary" disabled={busy} onClick={()=>act(confirmation.run,'Perubahan disimpan')}>Ya, lanjutkan</button></div></Modal>}
    {error&&(auth||credential||reminder||backup||confirmation)&&<div role="alert" className="modal-error">{error}<button className="icon-button" onClick={()=>setError('')}><X size={16}/></button></div>}
  </div>;
}
function Stat({title,value,caption,icon,alert=false}:any) {return <div className="stat"><div className="stat-top"><span>{title}</span><div className={'stat-icon '+(alert?'orange':'')}>{icon}</div></div><strong>{value.toString().padStart(2,'0')}</strong><p>{caption}</p></div>;}
function Empty({icon,title,text}:any) {return <div className="empty"><div>{icon}</div><h3>{title}</h3><p>{text}</p></div>;}
function Modal({title,subtitle,children,onClose,wide=false}:any) {
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[onClose]);
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section role="dialog" aria-modal="true" aria-label={title} className={'modal '+(wide?'wide':'')}><div className="modal-heading"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button className="icon-button" aria-label="Tutup dialog" onClick={onClose}><X size={20}/></button></div>{children}</section></div>;
}
function AuthModal({initialized,busy,onClose,onSubmit}:any) {
  const [password,setPassword]=useState(''),[confirm,setConfirm]=useState('');
  return <Modal title={initialized?'Buka vault':'Buat master password'} subtitle={initialized?'Credential akan dibuka hanya di sesi ini.':'Minimal 12 karakter. Simpan password di tempat aman; tidak ada reset password.'} onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSubmit(password);}}><label>Master password<input autoFocus type="password" minLength={initialized?1:12} maxLength={1024} required autoComplete={initialized?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label>{!initialized&&<label>Ulangi master password<input type="password" required autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>}<div className="modal-footer"><button type="button" className="secondary" onClick={onClose}>Batal</button><button className="primary" disabled={busy||(!initialized&&password!==confirm)}>{busy?'Memproses…':initialized?'Buka vault':'Buat vault'}</button></div></form></Modal>;
}
function CredentialModal({initial,busy,onClose,onSave,onGenerate,onDelete}:any) {
  const [c,setC]=useState<Credential>(initial),[show,setShow]=useState(false),[failure,setFailure]=useState('');
  const field=(key:keyof Credential,value:string)=>setC(c=>({...c,[key]:value}));
  useEffect(()=>{if(!show)return;const t=setTimeout(()=>setShow(false),15000);return()=>clearTimeout(t);},[show]);
  return <Modal title={c.id?'Edit credential':'Credential baru'} subtitle="Semua field credential dienkripsi dengan master password." onClose={onClose} wide><form onSubmit={e=>{e.preventDefault();onSave(c);}}><div className="form-grid"><label>Nama credential<input autoFocus required maxLength={160} placeholder="Contoh: VPS production" value={c.title} onChange={e=>field('title',e.target.value)}/></label><label>Kategori<select value={c.category} onChange={e=>field('category',e.target.value)}>{['Akun','Server','Billing','Lainnya'].map(v=><option key={v}>{v}</option>)}</select></label></div><label>Username / email<input value={c.username} onChange={e=>field('username',e.target.value)} autoComplete="off" placeholder="root atau nama@email.com"/></label><label>URL / host / IP<input value={c.url} onChange={e=>field('url',e.target.value)} placeholder="https://… atau 192.168.1.10:22"/></label><label>Password / token<div className="password-field"><input aria-label="Password / token" type={show?'text':'password'} value={c.password} onChange={e=>field('password',e.target.value)} autoComplete="new-password"/><button type="button" className="icon-button" title={show?'Sembunyikan':'Lihat selama 15 detik'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button><button type="button" className="icon-button" title="Generate password" onClick={async()=>{try{field('password',await onGenerate());}catch(e){setFailure((e as Error).message);}}}><RefreshCw size={18}/></button></div></label>{failure&&<p className="inline-error">{failure}</p>}<label>Catatan rahasia<textarea rows={3} value={c.notes} onChange={e=>field('notes',e.target.value)} placeholder="Recovery code, detail akses, atau informasi tambahan…"/></label><div className="modal-footer">{c.id&&<button type="button" className="danger-text" onClick={onDelete}>Hapus credential</button>}<span className="grow"/><button type="button" className="secondary" onClick={onClose}>Batal</button><button className="primary" disabled={busy}>Simpan credential</button></div></form></Modal>;
}
function ReminderModal({initial,busy,onClose,onSave}:any) {
  const [r,setR] = useState<Reminder>({...initial,mode:initial.mode ?? 'deadline'});
  const ongoing = r.mode === 'ongoing';
  const set = (key:keyof Reminder,value:any) => setR(r=>({...r,[key]:value}));
  const changeMode = (mode:'deadline'|'ongoing') => setR(r=>({
    ...r,mode,
    recurrence:mode === 'ongoing' && r.recurrence === 'once' ? 'daily' : r.recurrence,
    leadMinutes:0,repeatMinutes:0
  }));
  return <Modal title={r.id?'Edit reminder':r.kind==='bill'?'Bill baru':'Task baru'} subtitle="Atur jadwal dan kapan kamu ingin diingatkan." onClose={onClose} wide>
    <form onSubmit={e=>{e.preventDefault();onSave(r);}}>
      <label>Judul<input autoFocus required maxLength={160} placeholder={r.kind==='bill'?'Contoh: Perpanjangan VPS':'Contoh: Lanjutkan belajar bahasa'} value={r.title} onChange={e=>set('title',e.target.value)}/></label>
      {r.kind === 'task' && <label>Mode task
        <select value={r.mode} onChange={e=>changeMode(e.target.value as 'deadline'|'ongoing')}>
          <option value="ongoing">Tanpa deadline — ulang sampai selesai</option>
          <option value="deadline">Dengan deadline / jatuh tempo</option>
        </select>
      </label>}
      {r.kind==='bill'&&<div className="form-grid">
        <label>Nominal<input type="number" min="0" max="1000000000000000" step="0.01" required value={r.amount} onChange={e=>set('amount',Number(e.target.value))}/></label>
        <label>Mata uang<select value={r.currency} onChange={e=>set('currency',e.target.value)}>{['IDR','USD','EUR','SGD'].map(v=><option key={v}>{v}</option>)}</select></label>
      </div>}
      <div className="form-grid">
        <label>{ongoing?'Mulai pengingat (waktu lokal)':'Jatuh tempo (waktu lokal)'}
          <input required step="1" type="datetime-local" min="2000-01-01T00:00" max="2200-12-31T23:59:59" value={localDate(r.due)} onChange={e=>{if(e.target.value)set('due',new Date(e.target.value).toISOString());}}/>
        </label>
        <label>Jadwal berulang<select value={r.recurrence} onChange={e=>set('recurrence',e.target.value)}>
          {Object.entries(names).filter(([v])=>!ongoing||v!=='once').map(([v,label])=><option key={v} value={v}>{label}</option>)}
        </select></label>
      </div>
      {r.recurrence==='custom'&&<div className="form-grid">
        <label>Setiap<input type="number" required min="1" max="365" value={r.every} onChange={e=>set('every',Number(e.target.value))}/></label>
        <label>Satuan<select value={r.unit} onChange={e=>set('unit',e.target.value)}>{Object.entries(units).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>
      </div>}
      {!ongoing&&<div className="form-grid">
        <label>Ingatkan sebelum jatuh tempo<select value={r.leadMinutes} onChange={e=>set('leadMinutes',Number(e.target.value))}>{[[0,'Saat jatuh tempo'],[30,'30 menit sebelumnya'],[60,'1 jam sebelumnya'],[1440,'H-1'],[4320,'H-3'],[10080,'H-7']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>
        <label>Ulang notifikasi sampai selesai<select value={r.repeatMinutes} onChange={e=>set('repeatMinutes',Number(e.target.value))}>{[[0,'Tidak diulang'],[5,'Setiap 5 menit'],[15,'Setiap 15 menit'],[30,'Setiap 30 menit'],[60,'Setiap 1 jam'],[240,'Setiap 4 jam'],[1440,'Setiap hari']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>
      </div>}
      <div className="form-hint">{ongoing
        ? 'Waktu mulai menentukan jam pengingat, bukan batas penyelesaian. Pengingat terus muncul sesuai jadwal sampai task ditandai Selesai atau dinonaktifkan. Contoh: Harian mulai pukul 09.00 berarti setiap hari pukul 09.00.'
        : 'Jadwal berulang membuat periode berikutnya setelah selesai/bayar. Ulang notifikasi berlaku untuk periode yang masih terbuka.'}</div>
      <div className="channel-options">
        <label className="checkbox"><input type="checkbox" checked={r.windows} onChange={e=>set('windows',e.target.checked)}/><Bell size={17}/>Notifikasi Windows</label>
        <label className="checkbox"><input type="checkbox" checked={r.discord} onChange={e=>set('discord',e.target.checked)}/>Discord webhook</label>
      </div>
      <label>Catatan (tidak dienkripsi)<textarea rows={2} value={r.notes} maxLength={10000} onChange={e=>set('notes',e.target.value)} placeholder="Jangan isi password atau token di sini."/></label>
      <div className="modal-footer"><button type="button" className="secondary" onClick={onClose}>Batal</button><button className="primary" disabled={busy}>Simpan reminder</button></div>
    </form>
  </Modal>;
}
function SettingsPanel({settings,busy,act,unlocked,onUnlock,onBackup}:any) {
  const [autoStart,setAutoStart]=useState(settings.autoStart),[autoLock,setAutoLock]=useState(settings.autoLockMinutes),[webhook,setWebhook]=useState(''),[remove,setRemove]=useState(false);
  return <div className="settings-stack"><section className="panel settings-panel"><div className="section-title"><Settings size={20}/><h2>Aplikasi & keamanan</h2></div><label className="setting-row"><div><strong>Jalankan saat login Windows</strong><p>{settings.packaged?'Anchor mulai di system tray.':'Tersedia setelah aplikasi diinstal melalui installer.'}</p></div><input type="checkbox" disabled={!settings.packaged} checked={autoStart} onChange={e=>setAutoStart(e.target.checked)}/></label><label className="setting-row"><div><strong>Kunci vault setelah tidak aktif</strong><p>Vault juga dikunci saat jendela ditutup atau Windows terkunci.</p></div><select value={autoLock} onChange={e=>setAutoLock(Number(e.target.value))}>{[1,5,15,30].map(v=><option key={v} value={v}>{v} menit</option>)}</select></label><div className="setting-row"><div><strong>Zona waktu</strong><p>{settings.timezone} · Mengikuti zona waktu Windows. Periksa jadwal setelah mengganti zona waktu.</p></div></div></section>
    <section className="panel settings-panel"><div className="section-title"><Bell size={20}/><h2>Notifikasi</h2><span className={'badge '+(settings.hasWebhook?'green':'neutral')}>{settings.hasWebhook?'Webhook tersimpan':'Discord belum diatur'}</span></div><p className="muted">Buat webhook di channel privat Discord → Edit Channel → Integrations → Webhooks. Judul reminder dan waktu pengingat atau jatuh tempo dikirim ke channel tersebut.</p><label>Discord webhook URL<input type="password" autoComplete="off" placeholder={settings.hasWebhook?'Tersimpan. Isi hanya untuk mengganti.':'https://discord.com/api/webhooks/…'} value={webhook} onChange={e=>setWebhook(e.target.value)}/></label>{settings.hasWebhook&&<label className="checkbox"><input type="checkbox" checked={remove} onChange={e=>setRemove(e.target.checked)}/>Hapus webhook tersimpan saat menyimpan</label>}<p className="form-hint">Webhook dilindungi oleh akun Windows agar pengiriman tetap berjalan saat vault terkunci. Backup tidak menyertakan webhook; atur ulang setelah pindah perangkat.</p><div className="button-row"><button className="secondary" disabled={busy} onClick={()=>act(()=>api('testWindows'),'Notifikasi tes dikirim ke Windows')}>Tes Windows</button><button className="secondary" disabled={busy||!settings.hasWebhook} onClick={()=>act(()=>api('testDiscord'),'Pesan tes dikirim ke Discord')}>Tes Discord</button></div>{settings.lastDeliveryError&&<div className="inline-error">{settings.lastDeliveryError}</div>}</section>
    <div className="save-settings"><button className="primary" disabled={busy} onClick={()=>act(async()=>{await api('saveSettings',{autoStart,autoLockMinutes:autoLock,webhook,removeWebhook:remove});setWebhook('');setRemove(false);},'Pengaturan disimpan')}>Simpan pengaturan</button></div>
    {settings.automaticBackup&&<AutomaticBackupPanel settings={settings.automaticBackup} busy={busy} unlocked={unlocked} onUnlock={onUnlock} act={act}/>}
    <section className="panel settings-panel"><div className="section-title"><ShieldCheck size={20}/><h2>Backup & pemulihan</h2></div><p className="muted">Backup manual memakai password backup pilihanmu. Untuk file backup otomatis, masukkan master password vault asal saat backup dibuat. Pemulihan menggabungkan data; item dengan ID yang sudah ada tetap dipertahankan.</p><div className="button-row"><button className="secondary" disabled={busy} onClick={()=>unlocked?onBackup('exportBackup'):onUnlock()}><Download size={16}/>Ekspor backup</button><button className="secondary" disabled={busy} onClick={()=>unlocked?onBackup('importBackup'):onUnlock()}><Upload size={16}/>Pulihkan backup</button></div><div className="data-path"><span>DATABASE LOKAL</span><code>{settings.dataPath}</code></div><p className="form-hint">Credential terenkripsi; judul, jadwal, nominal, dan riwayat reminder tidak terenkripsi. Clipboard dibersihkan setelah 30 detik, tetapi riwayat clipboard Windows dapat menyimpan salinan.</p></section>
  </div>;
}
function BackupModal({mode,busy,onClose,onSubmit}:any) {const [password,setPassword]=useState(''),[confirm,setConfirm]=useState('');const exp=mode==='exportBackup';return <Modal title={exp?'Ekspor backup terenkripsi':'Pulihkan backup'} subtitle={exp?'Pilih password backup minimal 12 karakter. Simpan terpisah dari file backup.':'Untuk backup otomatis, gunakan master password vault asal. Untuk backup manual, gunakan password backup. Data yang sudah ada tidak ditimpa.'} onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSubmit(password);}}><label>Password backup<input type="password" required autoFocus minLength={exp?12:1} maxLength={1024} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="off"/></label>{exp&&<label>Ulangi password backup<input required type="password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>}<div className="modal-footer"><button className="secondary" type="button" onClick={onClose}>Batal</button><button className="primary" disabled={busy||(exp&&password!==confirm)}>{exp?'Pilih lokasi penyimpanan':'Pilih file backup'}</button></div></form></Modal>;}
createRoot(document.getElementById('root')!).render(<App/>);
